[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/test"
healthcheckTimeout = 300

[env]
MONGODB_URI = "${{shared.MONGODB_URI}}"
JWT_SECRET = "${{shared.JWT_SECRET}}"
NODE_ENV = "${{shared.NODE_ENV}}"
PORT = "${{shared.PORT}}"
REACT_APP_API_URL = "https://${{RAILWAY_PUBLIC_DOMAIN}}" 